---
- name: Output config information
  debug:
    msg: 
     - "Username: {{ username }}"
     - "Firefox Path: {{ firefox_path }}"
     - "Profile Name: {{ profile_name }}"

- name: check wether profile already
  find:
    paths: "{{ firefox_path }}"
    patterns: '*.{{ profile_name }}'
    file_type: directory
  register: profile

- name: set old profile as path
  set_fact:
    profile_path: "{{ profile.files[0].path }}"
  when: profile.matched

- name: create directory for config
  file:
    path: "{{ firefox_path }}/{{ profile_hash }}.{{ profile_name }}"
    state: directory
    recurse: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  when: not profile.matched

- name: set new profile as path
  set_fact:
    profile_path: "{{ firefox_path }}/{{ profile_hash }}.{{ profile_name }}"
  when: not profile.matched

- name: create directory for config
  template:
    src: templates/profiles.ini.j2
    dest: "{{ firefox_path }}/profiles.ini"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  when: not profile.matched
