---
- name: add search engines
  template:
    src: templates/bookmarks.j2
    dest: "{{ profile_path }}/bookmarks.html"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  notify: remove old searchengines
